# Generated by Django 5.1.5 on 2026-05-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('world', '0002_remove_adventure_locations_alter_location_adventure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercharacter',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='world.adventure'),
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='world.location'),
        ),
    ]
