# Generated by Django 5.1.5 on 2026-05-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='locations',
        ),
        migrations.AlterField(
            model_name='location',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='world.adventure'),
        ),
    ]
