# Generated by Django 5.1.5 on 2026-05-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_remove_adventure_locations_alter_location_adventure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField(default=30)),
                ('defense', models.IntegerField(default=10)),
                ('attack_bonus', models.IntegerField(default=2)),
                ('damage_die', models.IntegerField(default=6)),
                ('damage_bonus', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='world.adventure')),
            ],
        ),
    ]
