services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_rpg
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend_net

  redis:
    image: redis:7
    restart: always
    networks:
      - backend_net

  backend:
    build: ./backend
    env_file:
      - .env.docker
    volumes:
      - ./backend:/app

    user: "${UID:-1000}:${GID:-1000}"
    
    ports:
      - "8001:8000"
    command: /app/entrypoints/web.sh
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - backend_net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  celery:
    build: ./backend
    env_file:
      - .env.docker
    command: celery -A app worker -l info --concurrency=1
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - backend_net
    profiles: ["full"]

  celery-beat:
    build: ./backend
    env_file:
      - .env.docker
    command: celery -A app beat -l info --max-interval=30
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - backend_net
    profiles: ["full"]

networks:
  backend_net:
    driver: bridge

volumes:
  db_data: