# Generated by Django 5.1.5 on 2026-06-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.CharField(choices=[('lobby', 'Lobby'), ('in_game', 'In Game')], default='lobby', max_length=20),
        ),
    ]
