# Generated by Django 5.1.5 on 2026-09-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_playercharacter_adventure_and_more'),
        ('chat', '0004_alter_roomparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_participations', to='accounts.playercharacter'),
        ),
    ]
