# Generated by Django 5.1.5 on 2026-05-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('world', '0002_remove_adventure_locations_alter_location_adventure'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='world.adventure')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='chat.room')),
            ],
        ),
    ]
