# Generated by Django 5.1.5 on 2026-05-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('story', 'Story'), ('choice', 'Choice'), ('combat', 'Combat'), ('item', 'Item'), ('status', 'Status'), ('quest', 'Quest'), ('shop', 'Shop'), ('treasure', 'Treasure')], default='story', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('required_flags', models.JSONField(blank=True, default=list)),
                ('blocking_flags', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('consequences', models.JSONField(blank=True, default=dict)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='world.adventure')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_events', to='world.location')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='accounts.playercharacter')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.playercharacter')),
            ],
        ),
    ]
