# Generated by Django 5.1.5 on 2026-05-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_flag_alter_gameevent_event_type_and_more'),
        ('world', '0002_remove_adventure_locations_alter_location_adventure'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='world.adventure'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_events', to='world.location'),
        ),
    ]
