# Generated by Django 5.1.5 on 2026-05-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_adventure_alter_gameevent_location'),
        ('world', '0002_remove_adventure_locations_alter_location_adventure'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flag',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='flag',
            name='player',
        ),
        migrations.RemoveIndex(
            model_name='gameevent',
            name='game_gameev_adventu_4c93bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameevent',
            name='game_gameev_player__c17396_idx',
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_type',
            field=models.CharField(choices=[('story', 'Story'), ('choice', 'Choice'), ('combat', 'Combat'), ('item', 'Item'), ('status', 'Status'), ('quest', 'Quest'), ('shop', 'Shop'), ('treasure', 'Treasure')], default='story', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='world.adventure'),
        ),
        migrations.DeleteModel(
            name='Flag',
        ),
    ]
