# Generated by Django 5.1.5 on 2026-06-19 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_playercharacter_adventure_and_more'),
        ('game', '0004_alter_flag_unique_together_remove_flag_adventure_and_more'),
        ('world', '0003_enemy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='adventure',
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_type',
            field=models.CharField(choices=[('story', 'Story'), ('choice', 'Choice'), ('combat', 'Combat'), ('item', 'Item'), ('status', 'Status'), ('quest', 'Quest'), ('shop', 'Shop'), ('treasure', 'Treasure')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='gameevent',
            index=models.Index(fields=['adventure', 'timestamp'], name='game_gameev_adventu_4c93bd_idx'),
        ),
        migrations.AddIndex(
            model_name='gameevent',
            index=models.Index(fields=['player', 'timestamp'], name='game_gameev_player__c17396_idx'),
        ),
        migrations.AddField(
            model_name='flag',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.adventure'),
        ),
        migrations.AddField(
            model_name='flag',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('adventure', 'player', 'name')},
        ),
    ]
