# Generated by Django 5.1.5 on 2026-06-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_flag_remove_gamesession_adventure_and_more'),
        ('world', '0003_enemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='adventure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='world.adventure'),
            preserve_default=False,
        ),
    ]
